### ISSUE TITLE
Sporadic NoClassDefFoundError using Ruby Step

### ISSUE THREAD

**Issue by cosmocracy** [twineworks/ruby-for-pentaho-kettle#27] opened 2018-10-12 13:14 UTC
Similar to the issue reported in #26 we are, on occassion, getting `java.lang.NoClassDefFoundError` when using a Ruby Step.  Otherwise it's been working reliably and fantastically.  Any advice?  I'll place a couple of log snippets in the comments below.  We are using release `1.3.4` of the this plugin and I've verified it's using the included JRuby complete JAR (`9.1.13.0`).  Thanks for any ideas/avenues.

**Comment by cosmocracy** [comment] 2018-10-12 13:21
Here is one failure:

```
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - Process lines.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Error initializing step [Process lines] 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - Process lines.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : java.lang.NoClassDefFoundError: org/jruby/runtime/load/JarredScript 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - Process lines.0 - 	at org.jruby.runtime.load.LoadService.isJarfileLibrary(LoadService.java:657) 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - Process lines.0 - 	at org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:911) 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - Process lines.0 - 	at org.jruby.runtime.load.LoadService.smartLoadInternal(LoadService.java:531) 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - Process lines.0 - 	at org.jruby.runtime.load.LoadService.require(LoadService.java:402) 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - Process lines.0 - 	at org.jruby.Ruby.init(Ruby.java:1208) 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - Process lines.0 - 	at org.jruby.Ruby.newInstance(Ruby.java:339) 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - Process lines.0 - 	at org.jruby.embed.internal.LocalContext.getRuntime(LocalContext.java:117) 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - Process lines.0 - 	at org.jruby.embed.internal.SingleThreadLocalContextProvider.getRuntime(SingleThreadLocalContextProvider.java:61) 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - Process lines.0 - 	at com.twineworks.kettle.ruby.step.execmodels.SimpleExecutionModel.onInit(SimpleExecutionModel.java:72) 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - Process lines.0 - 	at com.twineworks.kettle.ruby.step.RubyStep.init(RubyStep.java:64) 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - Process lines.0 - 	at org.pentaho.di.trans.step.StepInitThread.run(StepInitThread.java:69) 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - Process lines.0 - 	at java.lang.Thread.run(Unknown Source) 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - tr_create_slideInvStage - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Step [Process lines.0] failed to initialize! 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - tr_create_slideInvStage - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Unable to prepare for execution of the transformation 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - tr_create_slideInvStage - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : org.pentaho.di.core.exception.KettleException:  
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - tr_create_slideInvStage - We failed to initialize at least one step.  Execution can not begin! 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - tr_create_slideInvStage -  
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - tr_create_slideInvStage -  
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - tr_create_slideInvStage - 	at org.pentaho.di.trans.Trans.prepareExecution(Trans.java:1157) 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - tr_create_slideInvStage - 	at org.pentaho.di.trans.Trans.execute(Trans.java:627) 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - tr_create_slideInvStage - 	at org.pentaho.di.job.entries.trans.JobEntryTrans.execute(JobEntryTrans.java:1152) 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - tr_create_slideInvStage - 	at org.pentaho.di.job.Job.execute(Job.java:724) 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - tr_create_slideInvStage - 	at org.pentaho.di.job.Job.execute(Job.java:865) 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - tr_create_slideInvStage - 	at org.pentaho.di.job.Job.execute(Job.java:865) 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - tr_create_slideInvStage - 	at org.pentaho.di.job.Job.execute(Job.java:865) 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - tr_create_slideInvStage - 	at org.pentaho.di.job.Job.execute(Job.java:609) 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - tr_create_slideInvStage - 	at org.pentaho.di.job.entries.job.JobEntryJobRunner.run(JobEntryJobRunner.java:69) 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:47 - tr_create_slideInvStage - 	at java.lang.Thread.run(Unknown Source) 
2018-10-12 08:37:49.251-0400 [info]   [stderr] 2018/10/12 08:37:48 - Kitchen - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Finished with errors 
2018-10-12 08:37:49.251-0400 [info]   [stderr] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=2048m; support was removed in 8.0
2018-10-12 08:37:49.258-0400 [ERROR]  SCHEDULER-280  Process terminated with exit code 1 (0x1)
```

**Comment by cosmocracy** [comment] 2018-10-12 13:27
PS, I have expertise in both Java and Ruby and would be very open to helping troubleshoot this deeper if you have any suggested angles to investigate.  One possibility we toyed with is that the step was ending for some unrelated reason and perhaps the plugin just didn't have enough bullet-proofing in the exception handling.  And it's vexing that this only happens "on occasion".

**Comment by slawo-ch** [comment] 2018-10-13 09:17
Hm, I'm going to have to guess, since you say its not easy to reproduce. Is there any chance at all that there are two jruby jars on the class path? The errors you are seeing seem consistent with an old jruby being on the classpath somehow. Maybe in the plugin folder, maybe in another plugin, maybe in pdi/lib. If the new ruby tries to initialize itself and looks for classes and the old ruby package is found first, it might break like this.

**Comment by slawo-ch** [comment] 2018-10-31 10:59
closing out, as issue has no reproduction path and there seems to be no updates

**Closed by slawo-ch** 2018-10-31 10:59 UTC
